# yaml-language-server: $schema=./schema.json

logger:
  transport:
    target: pino-princess

server:
  host: '127.0.0.1'
  port: 1337

db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: postgres
