# yaml-language-server: $schema=./schema.json

logger:
  transport:
    target: pino-princess

server:
  host: 127.0.0.1
  port: 1337

db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: postgres

jwt:
  jwtSecret:
    - ENC[AES256_GCM,data:wTDWxPe6kIU1sbT+WGT3Mkl5bC4bJujfdWmfAsDm33aaxdNHaIjb8x1rGamyYIq5E3jroQ/dKRhWHHNslj2UY0HIvLWSZwD1bxW2DRg=,iv:aomMwk5jhsZBIBNt22LL4CdQ3CIEbLJg+6OqKbtoigc=,tag:kgFdlQk83sZOKVsXCJCThA==,type:str]
  algorithm: HS384
  sessionExpiresIn: 5m
  refreshExpiresIn: 1h

cookie:
  cookieSecret:
    - ENC[AES256_GCM,data:8ps+ENLgZ39kzlRchYIhF0e4DIwPojTWa0IvzCjb4qw32PZeAunH9nFjHfNT5wWGm02QhC3mT9+R9w+L8sQifNZue0i043e44EFujKoF,iv:yeM8lVliM+Ccf5S1BcEiu3o8xDy2+74KpRs3G99CSTU=,tag:PVxv5KpZN3JVmslDpZ4BXg==,type:str]
  options:
    httpOnly: true
    signed: true
    secure: false
    sameSite: lax

sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  lastmodified: '2024-09-17T12:42:57Z'
  mac: ENC[AES256_GCM,data:0aqJXIBOSrFVs08lwe5BoJKMIbolRwTcRtuFOPj6M9yENqNzPMFGDsYpwLVV2bmB9RJ/B5VXN4foqC9K/YCovWlypGFAUv5QJ1UsXWaky4dQp6aSM/Nv2KR3D1Llwukx27haauvfgTjPIX6JEy/y/jqtEaG9kPULo9BU7HglXE8=,iv:9rEprwgjDBBHvG9ysD+x7trPfyR9NlrXDHH7+17mEEk=,tag:4F4H6lXPuu9K4hxtDHcvSQ==,type:str]
  pgp:
    - created_at: '2024-09-17T12:42:56Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMAziTx7nJM+ZEAQv/Z0IwLv9Cq4MlRzT0x1hJz97R72WG/CD09VorQUAiX0el
        sEhCvx+9wT/h5F5lZKjRWPl0BLODcM/Mbm0OMNW9Q1gNmzhWcNJ5rQ20+mlL1vuT
        8cCA7ZpR6qBrt3wc438LO8lWsRrP5TGeqmSB8jj//0CZ6JAwzJGoe4E4Saii9xUj
        5Ss0cg9newXI6IQuxRw9Zoq0U/xwVCdtpdUIHzRIuR31hMJEJ4amqn3X8wU1Ef/a
        KMJg2PtBFhep2xKhkIq0BiiXVQjl6scsrUWq/RRhB/MazHEKjtY6mEVz0OW/1aPL
        K88chKW6//LO5gUGGyQfseupBPIOG/hZOA6J4Ur73e4V+aGYswrBoKcdGjBKYIXG
        CQ9GgAY5ScsORizsjmfn2EnKCqKi1gGrjBCfSrJpwikCwM1JtuDfxw1m9UqlyuoC
        +mbBCXJnrbAxE2n/hVLRDZpv7E0RwasPCnz8nxCeSucTQp6EJPRqRDyGV6M94Lpp
        50cQ/G381ZoQSZjHA6QV0l4B13VfntaAYiUwQe/VZqWRvM/gkXJThaLHT2dSaHce
        Hgppaq3MBZZQwirRdAyygXDp7fd1t6gK3B3rwDMY0XcWS1TJNRejXglpGrQUePVd
        7LRytu/cwkAcs01g+Gke
        =zDDd
        -----END PGP MESSAGE-----
      fp: FD4449837B4A4A16
  encrypted_suffix: Secret
  version: 3.5.0
