# yaml-language-server: $schema=./schema.json

logger:
  transport:
    target: pino/file
    options:
      destination: /tmp/fastify-example-app.log

server:
  host: '0.0.0.0'
  port: ${PORT}

db:
  host: postgres
  port: 5432
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DB}

jwt:
  jwtSecret:
    - ENC[AES256_GCM,data:nuIFSaow6q/xPighked0GzvRVP/DjFZOqBqn7Ri+Qlx+T8yuEJms9JgX/DUZFxUnPwof2YEPFNVXAxa+qg1qFQ==,iv:mWllTy7sD4LzekdHVqv5Q7dZeZBKrS6wcNWk6YJqPxU=,tag:b1tA/2hhuvbuUjOfMWnsjA==,type:str]
  algorithm: RS512
  sessionExpiresIn: 15m
  refreshExpiresIn: 1d

cookie:
  cookieSecret:
    - ENC[AES256_GCM,data:33rxkDsh8hLrCCEQAvcgwDC9FS4xmcps4xJXRADbbSvVVakYagylDymua0/gp/jDMi7RBbWhOnczxqJhqjJz4g==,iv:hR+2hKXZa/diX2YUyZOktMI7hUTAuODLsHEciQhBBlM=,tag:B8uhuLa5OzQpybFqEE6x8A==,type:str]
  options:
    httpOnly: true
    signed: true
    secure: true
    sameSite: strict

sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  lastmodified: '2024-09-17T12:33:31Z'
  mac: ENC[AES256_GCM,data:mP3hpjTNKFtrCBi0oHuxCugnhmVjx0Tdzm2KvEduExocJUW3oDn0RS0w04JIq623V1sM/PF6FYEXOjjoXwMl6IKlbRMYFCun2E0ejM5EWqwlL2fQ0pIG/bUgCzC4XiJAeUYE6yeqXEDuupknPKnoUmg32AVwpNOphGc+bVrii+M=,iv:Jem01Cs0oBO0UNBBzdFQ1DBJHr7/PzT2EehpBT9KCjg=,tag:z0wCZesbPY+qamMg6+zEhA==,type:str]
  pgp:
    - created_at: '2024-09-17T12:33:31Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMAziTx7nJM+ZEAQv/WvEU4E5Gr4WTTKHOav75/6MqyNHb2ys91l51XtsU0zwH
        4sgr/IMHgDLE//TKfwNufoFb65XpQJgsN6KzFuA2PowChfRkSXLDGtCOvzGJa7fI
        Q6CVp6XlLrnDjMRqFWNq4z8SzpDXeSETWYQx70cjNVQYD3VYnmWQYrQFulxdXJPC
        OcTuG/r1k5QMFMMRyKhGmTBJx+KsJV7ceaVy6CubWYKjrX9zE3SbLhTGU0M6neUf
        RVTQqj+B7YqM9ww6YRyDjlsNP/bU5pwYTI0NArMvmNb6L8QH1tqYBxzGfzEEXj6S
        nuERMWOe9TC8qZNvE4Yxcx/j59qBPm5szlcruGnKcbqB/8RD2fruUcPvYGcWHf6Z
        94gsYgF51DjPUrJkXTNttxZEQAI5bygTkFKDSmE57qdz8oNU0HU6dhRw9nDL+YeL
        aAIEas49ndRUEYeBaap8RsT1GNn3ftxaCSre/qWV1zOLUq6q+dH+zrtcLBsnqYs9
        kqXvI2rjJRiv/vTlZOkb0l4BzMedJvIi4t/bFVKB1ro4XtfdLyWODkMJOD0ahTKS
        iz+r/IpxPYpZsQSOakLHiFoiAaKNIYiV0f8zrHe0Fdm81Hw7ynAf0RB+yV3DsUvG
        vatruIhVADFzYW3oYgy3
        =6Ax7
        -----END PGP MESSAGE-----
      fp: FD4449837B4A4A16
  encrypted_suffix: Secret
  version: 3.5.0
