# yaml-language-server: $schema=./schema.json

logger:
  transport:
    target: 'pino/file'
    options:
      destination: /tmp/fastify-example-app.log`

server:
  host: '0.0.0.0'
  port: ${PORT}

db:
  host: postgres
  port: 5432
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DB}
