# yaml-language-server: $schema=./schema.json

logger: false

server:
  host: '127.0.0.1'
  port: 0

db:
  host: localhost
  port: 5432
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DB}

jwt:
  jwtSecret:
    - ENC[AES256_GCM,data:3zykVBU67mu/YNE4EnNBZN3KbWsRKUFagwfdNUsKo63a,iv:4jy+PWd8ZPs15tMcvmcDdCfwGwSAJ2vz1KfCjmQzkIA=,tag:y/ZnZmU6Z1TBKpEUuaPpiA==,type:str]
  algorithm: HS256
  sessionExpiresIn: 1m
  refreshExpiresIn: 5m

cookie:
  cookieSecret:
    - ENC[AES256_GCM,data:eLUSBr7//urCfC4/3nlWDGLvVlDflKZcG4F+MBU3hodD,iv:FxS5DXumf7wi02FlxCfvRU48YpXGX0e3AYwT2FAx2wE=,tag:9x7Lnxa4caQhMnUVfTRglw==,type:str]
  options:
    httpOnly: true
    signed: true
    secure: false
    sameSite: lax
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  lastmodified: '2024-09-17T12:46:18Z'
  mac: ENC[AES256_GCM,data:FzlWbpu0QelyCXURJSY8xRgNhI9MWfhBVtUSRY260PCJpYEnzHsd6T1ridlcttvyYCIrEEBl+8wZH0HgPwsCEQi/2FrqZt8f69bpjTdrTboB2m3NMKwccfkKep73HJSvq6vrM8WZ+0HM30rTJ3GVBDG0WcJMxDyce8tb+I+mkTg=,iv:OyjCKlOgj4Wd+fkXUEUbMB64IeZvxtGsMJkvxBhFmMs=,tag:LstuXcSC4eUGSLBebEM/jw==,type:str]
  pgp:
    - created_at: '2024-09-17T12:46:18Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMAziTx7nJM+ZEAQv9GEmBMPB+LfFJB+d3hMyp0+nC//B2gvMAm6gTIm15O5+U
        iGOdsLzBYGNFDNA98ahc5x2L1j4VR65y9RnCoIZJXnEiaA3R+dJcr8ftu98goVZc
        KJwNb3mqXL3YfR2Z9ZqG06cL6BSC7dN5LP3/mkWnl9YDZ85SEgU00iyfMUGvwiwa
        hJWYjfheO2Qj9d5K/lr0Iyu+m+bdp6z07F3v1a70kCsMfZSthEFRsLMa/msOz2Oj
        /1aOzFdZAcHwxG3uEhHGMZTWvTf31FFS9MQOvuiDVhJGPy81GOfiH2dHF/rbNeS9
        3BGZAIU1nTkLUJK8vRE/iOkIQpyrX7mCpLfJ8vq/KcujMvt3HoeZ70NQSmSZYQp4
        L1lajK7hO/ispfyvToDMlkBvPFKqWbVEBbBfu32IkKWoC4dT8vXcHYfeH3hwQHgM
        qyGoXWKS7iytTioXFdKccAPuz2MOZiIpEIKjr2sgXzEY9PzC2YRpKbPVvBlmDVDu
        7WJXHAl4PBfPm2WrY4uo0l4BX66Jed5LIJ3k7t3k2abHynIaAr+dYMNDOEkiNxNg
        4oqgqdWW8U1pRUInQ7Voo4U5fKqRXxDqEr7yncCpL34C411Si6yvlb3E82lK3KLZ
        0xwo5Kc6/TR417nLyWlG
        =1FdT
        -----END PGP MESSAGE-----
      fp: FD4449837B4A4A16
  encrypted_suffix: Secret
  version: 3.5.0
