# yaml-language-server: $schema=./schema.json

logger: false

server:
  host: '127.0.0.1'
  port: 0

db:
  host: localhost
  port: 5432
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DB}
